-- =============================================================================
-- send-z-report cron'u: her akşam TR 23:30 (UTC 20:30) gün sonu Z raporu push'u
-- (Esnafın dükkanı ~23:00 kapanıyor; 23:30 günün tamamını yakalar. 23:30 gece
--  yarısından önce olduğu için "bugün" TR tarihi doğru kalır.)
--
-- !!! BU DOSYA OTOMATİK UYGULANMAZ — sadece NO-OP notice verir.
--     Cron'un auth'u service-role JWT gerektirir ve JWT git'e GİREMEZ; ayrıca
--     Supabase'de `postgres` rolü `ALTER DATABASE ... SET app.settings.*` YAPAMAZ
--     (42501 permission denied). Bu yüzden GUC yöntemi bu projede çalışmaz.
--     (Aynı sebeple delete-scheduled-accounts-daily cron'unun GUC'u boş = auth kırık.)
--
-- DOĞRU YÖNTEM (mevcut çalışan process-scheduled-transactions / fetch-exchange-rates
-- cron'larıyla aynı): JWT'yi cron KOMUTUNA göm ve cron'u Dashboard > SQL Editor'da
-- ELLE planla. JWT cron.job.command'da kalır (git'te değil).
--
-- ETKİNLEŞTİRME (dışa dönük — 658 kullanıcı; önce dry-run ile doğrula):
--   1) Edge function deploy edildi: send-z-report (atıl; çağrılana dek bir şey göndermez).
--   2) DOĞRULA (göndermeden): Dashboard > Edge Functions > send-z-report > Invoke,
--      body {"dry_run":true} -> hedef sayıları + örnek metni gör.
--   3) SQL Editor'da AŞAĞIDAKİ komutu çalıştır (<SERVICE_ROLE_JWT> yerine
--      Dashboard > Settings > API > service_role 'eyJ...' anahtarını yapıştır):
--
--      SELECT cron.schedule(
--        'send-z-report-evening',
--        '30 20 * * *',  -- UTC 20:30 = TR 23:30
--        $cmd$
--        SELECT net.http_post(
--          url := 'https://ulohxpkhesxozwnlnonb.supabase.co/functions/v1/send-z-report',
--          headers := jsonb_build_object(
--            'Authorization', 'Bearer <SERVICE_ROLE_JWT>',
--            'Content-Type', 'application/json'
--          ),
--          body := '{}'::jsonb
--        );
--        $cmd$
--      );
--
-- GERİ ALMA:  SELECT cron.unschedule('send-z-report-evening');
-- NOT: delete-scheduled-accounts-daily de aynı şekilde JWT-gömülü yeniden planlanmalı.
-- =============================================================================
DO $$
BEGIN
  RAISE NOTICE 'send-z-report cron ELLE planlanir (yukaridaki SQL, gomulu JWT ile). Bu migration no-op.';
END $$;
